

### login
POST http://localhost/api/auth/login
Content-Type: application/json

{
    "email": "cong@gmail.com",
    "password":2345
}
### sign up
POST http://localhost/api/account/register
Content-Type: application/json

{
    "fullName" : "Conggu",
    "email": "cong1@yopmail.com",
    "password": 12345678,
    "password_confirmation":12345678
}
### confirm otp create account
POST http://localhost/api/account/confirm-registration
Content-Type: application/json

{
    "otp" :706620,
    "email": "cong1@yopmail.com"
}


### sent otp to reset account
POST http://ec2-13-231-114-148.ap-northeast-1.compute.amazonaws.com/api/password/email
Content-Type: application/json

{
   "email": "cong1@yopmail.com"

}

### confirm otp to reset account
POST http://ec2-13-231-114-148.ap-northeast-1.compute.amazonaws.com/api/password/confirm-reset
Content-Type: application/json

{
   "email": "cong1@yopmail.com",
    "otp" : 751323
    
}

### change account
POST http://ec2-13-231-114-148.ap-northeast-1.compute.amazonaws.com/api/password/reset
Content-Type: application/json

{
    "email":"cong1@yopmail.com",
    "password": 123456789,
    "password_confirmation":123456789
    

}


### profile
GET http://localhost/api/user/1000000/infor
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQiOjEwMDAwMTAsImV4cCI6MTY3NjU1MjUxMX0.auGyT7Z68wsiKuwC842oE-U3ZLy_F5nhQ2DuoXH4lv67Buje6fUaCBhT3HythsDJpnVQEZBTr-RVmsAk9Pge1w

### update profile
put http://localhost/api/user/update/1000000
Accept: multipart/form-data
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQiOjEwMDAwMTAsImV4cCI6MTY3NjU1MjUxMX0.auGyT7Z68wsiKuwC842oE-U3ZLy_F5nhQ2DuoXH4lv67Buje6fUaCBhT3HythsDJpnVQEZBTr-RVmsAk9Pge1w
{
    "fullName":"dkfjkdlfj",
    "avatar":
}







### Parking lot=================================


### get all parking lot

GET http://localhost/api/parking-lot
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQiOjEwMDAwMDAsImV4cCI6MTY3NjcyNzUwM30.DBsaiLINNbTsKhWw9erY-TfZF6SYzs0nk3sLb5iqiFLrqNE3vFAOsx-i7XFC4QQBN4_yQtd7Ac944CZbzF18sg



### location near you 

GET http://localhost/api/parking-lot/location
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQiOjEwMDAwMDAsImV4cCI6MTY3Njc0NDE2Nn0.-PFdWp2-PA8aW4YzcnJqlocirVoN4M6G07OuBkJH85aQdNE49VcU20HISP5Y1fYwVrDZPMrAgGTi8pcrV8mTyg

{
    "latitude":16.060832,
    "longitude":108.241491
}

### get comment of parking lot

GET http://localhost/api/parking-lot/1000000/info/comment
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQiOjEwMDAwMDAsImV4cCI6MTY3NjcyNzUwM30.DBsaiLINNbTsKhWw9erY-TfZF6SYzs0nk3sLb5iqiFLrqNE3vFAOsx-i7XFC4QQBN4_yQtd7Ac944CZbzF18sg

