

### login
POST http://13.231.114.148/api/auth/login
Content-Type: application/json

{
    "email": "cong@gmail.com",
    "password":12345
}
### sign up
POST http://ec2-13-231-114-148.ap-northeast-1.compute.amazonaws.com/api/account/register
Content-Type: application/json

{
    "fullName" : "Conggu",
    "email": "cong2@yopmail.com",
    "password": 12345678,
    "password_confirmation":12345678
}
### confirm otp create account
POST http://localhost/api/account/confirm-registration
Content-Type: application/json

{
    "otp" :998226,
    "email": "cong1@yopmail.com"
}


### sent otp to reset account
POST http://localhost/api/password/email
Content-Type: application/json

{
   "email": "cong@yopmail.com"

}

### confirm otp to reset account
POST http://localhost/api/password/confirm-reset
Content-Type: application/json

{
   "email": "cong@yopmail.com",
    "otp" : 376086
    
}

### change account
POST http://localhost/api/password/reset
Content-Type: application/json

{
    "email":"congdev@gmail.com",
    "password": 12345678,
    "password_confirmation":12345678
    

}
###
POST http://localhost/api/test 
Content-Type: application/json

{
    "name": "cong"
}

### profile
GET http://localhost/api/user/1000000
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQiOjEwMDAwMDAsImV4cCI6MTY3NjExODE5OH0.hZZZbUoSdFruyNkC6fwASDNUs3waRAAeR9Vc8hhhdLLtmhGG5d2L0-vJD4bvhpE96YN41cC4-nJQ8J9KFALWLw
